services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    expose:
      - 5432

  backend:
    image: ${DOCKER_BACKEND_IMAGE}
    command: sh -c "
      poetry run alembic upgrade head &&
      poetry run uvicorn src.core:app --host 0.0.0.0 --port 8000"
    expose:
      - 8000
    volumes:
      - ./.env:/var/www/app/.env
    restart: always
    depends_on:
      - db

  frontend:
    image: ${DOCKER_FRONTEND_IMAGE}
    command: sh -c "quasar serve dist/spa --history -p 3000"
    volumes:
      - ./.env:/var/www/app/.env
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./robots.txt:/etc/nginx/conf.d/robots.txt
      - /etc/letsencrypt/live/ispent.ru/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/ispent.ru/privkey.pem:/etc/privkey.pem
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

volumes:
  pg-data:
