"""confirm table

Revision ID: 0f0b0e360491
Revises: ff47ce75ce09
Create Date: 2024-01-05 17:16:11.063684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0b0e360491'
down_revision: Union[str, None] = 'ff47ce75ce09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirm_token_id'), 'confirm_token', ['id'], unique=False)
    op.drop_index('ix_confirm_user_id', table_name='confirm_user')
    op.drop_table('confirm_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='confirm_user_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='confirm_user_pkey')
    )
    op.create_index('ix_confirm_user_id', 'confirm_user', ['id'], unique=False)
    op.drop_index(op.f('ix_confirm_token_id'), table_name='confirm_token')
    op.drop_table('confirm_token')
    # ### end Alembic commands ###
