"""pass2

Revision ID: 23c49a57bd78
Revises: 858ecb90ade3
Create Date: 2023-10-08 13:47:37.956439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c49a57bd78'
down_revision: Union[str, None] = '858ecb90ade3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
