"""added filed comment

Revision ID: 5563bff71156
Revises: a7d1afa41119
Create Date: 2023-11-01 22:37:58.006532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5563bff71156'
down_revision: Union[str, None] = 'a7d1afa41119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('comment', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'comment')
    # ### end Alembic commands ###
