"""added color/icon category user

Revision ID: 937ea0ebb199
Revises: e27f10ecae55
Create Date: 2023-11-22 16:16:24.465894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ea0ebb199'
down_revision: Union[str, None] = 'e27f10ecae55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_user', sa.Column('color', sa.String(length=255), nullable=False))
    op.add_column('category_user', sa.Column('icon', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_user', 'icon')
    op.drop_column('category_user', 'color')
    # ### end Alembic commands ###
