"""id telegram remove nullable

Revision ID: e27f10ecae55
Revises: ddf6b6b6150c
Create Date: 2023-11-16 14:52:09.772964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27f10ecae55'
down_revision: Union[str, None] = 'ddf6b6b6150c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_telegram',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_telegram',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
