name: CI/CD

on: workflow_dispatch
  # pull_request:
    # branches: [ master ]

jobs:
  build:
    name: Building an image and pushing it to hub
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v4

      - name: Build image
        run: echo 777
        # run: docker build -t grishchenkonikita/ispent:backend -f .\docker\Dockerfile .