name: ispent backend

on: workflow_dispatch
  # pull_request:
    # branches: [ master ]

jobs:
  build:
    name: Building an image and pushing it to hub
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .\docker\Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}




        # run: docker build -t grishchenkonikita/ispent:backend -f .\docker\Dockerfile .

  # deploy:
  #   - name: Run command on remote server
  #     needs: build
  #     uses: D3rHase/ssh-command-action@v0.2.2
  #     with:
  #       host: ${{secrets.SSH_HOST}}
  #       user: ${{secrets.SSH_USER}}
  #       private_key: ${{secrets.SSH_PRIVATE_KEY}}
  #       command: |
  #         cd ${{ secrets.PROJECT_FOLDER }};
  #         git checkout main;
  #         git pull;
  #         docker-compose --file docker-compose.prod.yml down;
  #         docker-compose --file docker-compose.prod.yml up -d;
  #         docker system prune --all --force;